server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5434/orderdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


# ============================================
# USER SERVICE URL
# ============================================
user:
  service:
    url: http://localhost:8081

# ============================================
# USER SERVICE URL
# ============================================
product:
  service:
    url: http://localhost:8082